#!/usr/bin/env bash
echo ""
echo "terminal compatible emoticons: "
echo "Tested with Putty"
echoo ""
echo ""
echo "✁ ✂ ✃   ✆ ✇ ✈ ✉ ✎ ✏ ✐ ✑ ✒ ✓ ✔ ✕ ✖ ✗ ✘ ✙ ✚ ✛ ✜ ✝ ✞ ✟"
echo ""
echo "❀ ❁ ❂ ❃ ❄ ❅ ❆ ❇ ❈ ❉ ❊ ❋ ❍ ❏ ❐ ❑ ❒ ❖ ❗ ❘ ❙ ❚"
echo ""
echo "⏴ ⏵ ⏶ ⏷ ⏸ ⏹ ⏺"
echo ""
echo "😀 😁 😂 🤣 😃 😄 😅 😆 😉 😊 😋 😎 😍 😘  😗 😙 😚 ☺ 🙂 🤗 "
echo ""
echo "🤔  😐 😑 😶 🙄 😏 😣 😥 😮 🤐 😯 😪 😫 😴 😌 😛 😜 😝 🤤 😒 😓 😔 😕 🙃 🤑 😲"
echo ""
echo "💋 💘 ❤ 💓 💔 💕 💖 💗 💙 💚 💛 🧡 💜 🖤 💝 💞 💟 ❣ 💌 💤 💢 💣 💥 💦 💨 💫 💬 🗨 🗯 💭 🕳"
echo ""
echo "♀ ♂🔱 📛 🔰 ⭕  ☑ ✔ ✖  〽 ✳ ✴ ❇ ‼  ❗ 〰 © ® ™"
echo ""
echo "🔋 🔌 💻 🖥 🖨  🖱 🖲 💽 💾 💿 📀 "
echo ""
echo "📀 🖳🖥⌨🖮 🖫🖬 "
echo ""

